[package]
name = "pido"
version = "0.1.0"
authors = ["i1i1"]
edition = "2018"

[dependencies]
cute = "0.3.0"
derive_more = "0.99.5"
gperftools = "0.2.0"
image = "0.23.2"
imageproc = "0.20.0"
minifb = "0.15.3"
rand = "0.7.3"
rayon = "1.3.0"
structopt = "0.3.12"

[profile.release]
debug = true
